"""Entry points: python -m port5g.cli {run|figures|assumptions|anchors|geometry-check}"""
from __future__ import annotations

import argparse
import sys
import warnings
from pathlib import Path

from .config import load_config


def cmd_run(a):
    from . import scenario
    cfg = load_config(warn=False)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        res = scenario.run(cfg, seed=a.seed)
    out = cfg.root / "results" / "results.json"
    scenario.save(res, out)
    lb = res["link_budgets"]["S1_control"]
    print(f"results -> {out}")
    print(f"  sites: {res['plan']['n_sites']} ({res['plan']['method']}), coverage {res['plan']['coverage_fraction']:.1%}")
    print(f"  S1 control UL MAPL {lb['ul']['mapl_db']:.1f} dB, radius {lb['radius_ul_m']:.0f} m, limiting: {lb['limiting']}")
    for p, c in res["capacity"]["by_pattern"].items():
        print(f"  TDD {p}: UL frac {c['ul_fraction']:.2f}, {c['ul_cell_mean_mbps']:.0f} Mbit/s/cell, {c['ul_network_mbps']:.0f} Mbit/s network "
              f"— closes: {c['closes']}; sites for capacity: {c['sites_needed_for_capacity_1layer']} (1L) / {c['sites_needed_for_capacity_2layer']} (2L UL MIMO)")
    print(f"  local UPF proof: {res['latency']['local_upf_proof']}")
    co = res["coexistence"]
    for p, v in co["by_pattern"].items():
        fr = v["conflict_fraction"]
        print(f"  coexistence {p} vs MNO {co['mno_pattern']}: {fr['ours_U_mno_D'] + fr['ours_D_mno_U']:.0%} conflict symbols, "
              f"extra isolation needed at nearest MNO site {v['extra_isolation_needed_db']:.1f} dB")
    for w in co["warnings"]:
        print(f"  !! {w}")
    ec = res["economics"]
    b = ec["scenarios"][ec["base_site_scenario"]]
    for opt, e in b.items():
        pb = "none within horizon" if e["use_case_payback_years"] is None else f"{e['use_case_payback_years']:.1f} y"
        print(f"  economics [{ec['base_site_scenario']}, {e['n_sites']} sites, {opt}]: network TCO {e['network_tco_discounted']/1e6:.2f} MEUR, "
              f"use-case NPV {e['use_case_npv']/1e6:.2f} MEUR, payback {pb}")
    if ec["n_unverified_inputs"]:
        print(f"  !! {ec['n_unverified_inputs']} economic inputs are [UNVERIFIED] placeholders — economics not reportable")
    if res["site"]["placeholder"]:
        print("  !! site geometry is a PLACEHOLDER — figures 1/2 and site count are not reportable")


def cmd_figures(a):
    from . import plots
    cfg = load_config(warn=False)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        made = plots.make_all(cfg.root / "results" / "results.json", cfg.root / "figures", cfg)
    for p in made:
        print("wrote", p)


def cmd_assumptions(a):
    cfg = load_config(warn=False)
    rows = sorted(cfg.registry, key=lambda p: (p.confidence != "unverified", p.path))
    lines = ["# Assumptions register (GENERATED by `make assumptions` from config/*.yaml — do not edit by hand)", "",
             f"Counts: {cfg.by_confidence()}", "",
             "| # | Path | Value | Unit | Confidence | Source | Impact if wrong |", "|---|---|---|---|---|---|---|"]
    for i, p in enumerate(rows, 1):
        conf = "**[UNVERIFIED]**" if p.unverified else p.confidence
        val = str(p.value).replace("|", "\\|")
        src = p.source.replace("|", "\\|").replace("\n", " ")
        lines.append(f"| {i} | `{p.path}` | {val} | {p.unit} | {conf} | {src} | see docs/impact_notes.md |")
    lines += ["", "## Manual notes (kept in docs/impact_notes.md)", "",
              "Model-structure assumptions that are not single config values (channel model per zone, blockage term, "
              "independent-error HARQ, ideal MRC gain, attenuated Shannon) are listed in docs/impact_notes.md."]
    out = cfg.root / "docs" / "assumptions.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    n = len(cfg.unverified())
    print(f"wrote {out}: {len(rows)} assumptions, {n} [UNVERIFIED]")
    if a.strict and n:
        print("STRICT: unverified values remain:", file=sys.stderr)
        for p in cfg.unverified():
            print("  -", p.path, file=sys.stderr)
        sys.exit(1)


def cmd_anchors(a):
    from . import capacity, channel, linkbudget
    print("UMi-SC LOS 3.7 GHz 100 m :", round(float(channel.umi_sc_los(100, 3.7, 10, 1.5, check=False)), 2), "(expect 85.76)")
    print("InF LOS   3.7 GHz 100 m :", round(float(channel.inf_los(100, 3.7)), 2), "(expect 85.64)")
    print("InF-DH NLOS 3.7 GHz 100m:", round(float(channel.inf_nlos(100, 3.7, 'InF-DH')), 2), "(expect 88.79)")
    print("Noise 100 MHz           :", round(linkbudget.thermal_noise_dbm(100e6), 1), "(expect -94.0)")
    print("Noise 360 kHz           :", round(linkbudget.thermal_noise_dbm(360e3), 1), "(expect -118.4)")
    print("38.306 DL 4L 256QAM     :", round(capacity.data_rate_38306(4, 8, 1, 273, 1, 0.14)), "(expect 2337)")
    print("38.306 UL 1L 64QAM      :", round(capacity.data_rate_38306(1, 6, 1, 273, 1, 0.08)), "(expect 469)")


def cmd_geometry_check(a):
    from . import geometry
    cfg = load_config(warn=False)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        site = geometry.load_site(cfg)
    print(f"placeholder: {site.placeholder}; area {site.area_ha:.1f} ha; quay {site.quay.length:.0f} m")
    for z in site.zones:
        print(f"  zone {z}: {site.zones[z].area/1e4:.1f} ha, clutter density r={site.clutter_density(z):.2f}")
    if not 70 <= site.area_ha <= 110:
        print("WARNING: area outside 70-110 ha (brief §1.1 range)")


def main(argv=None):
    ap = argparse.ArgumentParser(prog="port5g")
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("run"); r.add_argument("--seed", type=int, default=None); r.set_defaults(fn=cmd_run)
    sub.add_parser("figures").set_defaults(fn=cmd_figures)
    s = sub.add_parser("assumptions"); s.add_argument("--strict", action="store_true"); s.set_defaults(fn=cmd_assumptions)
    sub.add_parser("anchors").set_defaults(fn=cmd_anchors)
    sub.add_parser("geometry-check").set_defaults(fn=cmd_geometry_check)
    a = ap.parse_args(argv); a.fn(a)


if __name__ == "__main__":
    main()
